import random

def randomTip():
  number = random.randint(0,30)

  tips = []
  tips.append("Create a good and realistic budget.")
  tips.append("Track your expenses in a notebook.")
  tips.append("Get a summer job! Mow a neighbour's lawn and earn $20 quickly!")
  tips.append("Set realistic and easy to reach goals for your money.")
  tips.append("Make a list of your needs vs your wants.")
  tips.append("Time is your best friend! Start saving now and watch your money grow!")
  tips.append("Spend less money than you earn.")
  tips.append("Track your income in a notebook.")
  tips.append("Start building your credit today by co-signing a credit card with your parents.")
  tips.append("One in 5 teens have a credit card as an authorized user on a guardian's account.")
  tips.append("Only 46% of Canadians have a budget that they follow")
  tips.append("People with higher financial confidence get better results with debt management.")
  tips.append("People with a lower income are typically more financially educated.")
  tips.append("Make saving a habit. It will be worth it in the long run.")
  tips.append("Try discussing methods of payment with a parent/guardian today!")
  tips.append("Ask your parent/guardian to show you how to deposit money at the bank!")
  tips.append("Try discussing sales tax with a parent/guardian today!")
  tips.append("Try saving a dime for every dollar you recieve.")
  tips.append("Entering banking information on a not secured platform can lead to identity theft.")
  tips.append("The sooner you save, the faster your money can grow - from compound interest.")
  tips.append("Using a credit card is like taking out a loan. If you don't fully pay it back each month, you will pay more than you spent.")
  tips.append("Before making a purchase ask yourself: Do I really need this or would it just be nice to have?")
  tips.append("What is compound interest? \nWhen you earn interest on the original amount of money you put in AND its interest. It’s how your savings grow faster, the longer you leave them along! Examples: RESP, RRSP, savings account.")
  tips.append("What is a debit card? \nA card used as a payment method and takes away money directly from your bank account. It is very similar to cash.")
  tips.append("What is a credit card? \nA card that allows people to buy items without cash - it is similar to a loan from the bank. This loan must be repaid by the end of the month or else you will need to pay interest.")
  tips.append("What is investment? \nSomething we put our money in to help it grow. If we just keep out money in a piggy bank or drawer, it won’t earn money for us. Examples: Savings accounts, bonds, stocks.")
  tips.append("What is a budget? \nA plan for how much money will be spent and earned during a time period.")
  tips.append("What are taxes? \nA method the government uses to collect money from its citizens to pay for things people need like schools and roads. A percentage of money from the items we purchase will go to the government in the form of taxes.")
  tips.append("What is inflation? \nThe general level of prices goes up and each dollar is worth less than before. Your parents could have bought 10 candies with a dollar when they were your age, but you can only buy 1 candy with the same amount. This is due to inflation.")
  tips.append("What is debt? \nThe money one party owes another. Typically the borrower party has a limited amount of time to pay them back with interest.")
  tips.append("What is identity theft? \nWhen someone uses another person's personal information like their name, credit card number, social security number without their permission to commit fraud or other crimes.")
   
  print("\n---------------------------------\n|          Random Tip!          |\n---------------------------------\n"+tips[number])
